### ISSUE TITLE
Run DMD on the V matrix (of the `hourly` snapshot) 

### ISSUE THREAD

**Issue by LydiaFrance** [ClimeTrend/DMD-ERA5#1]
Run DMD using `hourly_v.npy` file as calculated using POD on Baskerville.

**Comment by LydiaFrance** [comment]
Currently blocked, unsure why the v matrix from Baskerville is square and how it has been defined, unsure where to find the code to create it. I could run DMD on this matrix but I wouldn't know how to interpret any of the results.

**Comment by louisavz** [comment]
Now covered by https://github.com/ClimeTrend/dmd-turing-proj-mgmt/issues/2
