### ISSUE TITLE
Create Python script for downloading ERA5 snapshots reproducibly

### ISSUE THREAD

**Issue by LydiaFrance** [ClimeTrend/DMD-ERA5#3]
To make this https://github.com/ClimeTrend/dmd-turing-proj-mgmt/issues/10 and https://github.com/ClimeTrend/dmd-turing-proj-mgmt/issues/15 reproducible in Baskerville, creating a script to download ERA5 snapshots, run the POD and then save associated metadata. 

First step before attempting https://github.com/ClimeTrend/dmd-turing-proj-mgmt/issues/14

**Comment by LydiaFrance** [comment]
### `era5-download.py`

### `era5-download-config.py`

### `data/00_era5/config.ini`

**Comment by dsj976** [comment]
Python library to parse time deltas when downloading ERA5 data: https://dateparser.readthedocs.io/en/latest/index.html

**Comment by LydiaFrance** [comment]
Looking into what settings will exist in the `config.ini` for the user to change. 

All should be strings

- `source_path`
- `start_date`
- `start_time`
- `end_date`
- `end_time`
- `delta_time`
- `variables`
- `levels`
- `save_name`

**Comment by dsj976** [comment]
Have moved `config.ini` to the project root (i.e. moving it out of `src`) following Nathan's advice, since `src` should only contain code
